const questionData = [
  {
    id: 1,
    question: "Rolex is a company that specializes in what type of product?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Phone", correct: false, probability: 10 },
      { option: "B", text: "Watches", correct: true, probability: 70 },
      { option: "C", text: "Food", correct: false, probability: 10 },
      { option: "D", text: "Cosmetics", correct: false, probability: 10 },
    ],
  },
  {
    id: 2,
    question: "When did the website 'Facebook' launch?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "2004", correct: true, probability: 70 },
      { option: "B", text: "2005", correct: false, probability: 10 },
      { option: "C", text: "2006", correct: false, probability: 10 },
      { option: "D", text: "2007", correct: false, probability: 10 },
    ],
  },
  {
    id: 3,
    question: "Who played the character of Harry Potter in the movie series?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Elijah Wood", correct: false, probability: 20 },
      { option: "B", text: "Daniel Radcliffe", correct: true, probability: 60 },
      { option: "C", text: "Rupert Grint", correct: false, probability: 10 },
      { option: "D", text: "Tom Felton", correct: false, probability: 10 },
    ],
  },
  {
    id: 4,
    question: "Which planet is known as the Red Planet?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Earth", correct: false, probability: 10 },
      { option: "B", text: "Mars", correct: true, probability: 70 },
      { option: "C", text: "Jupiter", correct: false, probability: 10 },
      { option: "D", text: "Venus", correct: false, probability: 10 },
    ],
  },
  {
    id: 5,
    question: "What is the capital city of Australia?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Sydney", correct: false, probability: 50 },
      { option: "B", text: "Melbourne", correct: false, probability: 30 },
      { option: "C", text: "Canberra", correct: true, probability: 20 },
      { option: "D", text: "Brisbane", correct: false, probability: 10 },
    ],
  },
  {
    id: 6,
    question: "What is the largest ocean on Earth?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Atlantic Ocean", correct: false, probability: 20 },
      { option: "B", text: "Indian Ocean", correct: false, probability: 20 },
      { option: "C", text: "Pacific Ocean", correct: true, probability: 50 },
      { option: "D", text: "Arctic Ocean", correct: false, probability: 10 },
    ],
  },
  {
    id: 7,
    question: "What is the smallest prime number?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "0", correct: false, probability: 10 },
      { option: "B", text: "1", correct: false, probability: 20 },
      { option: "C", text: "2", correct: true, probability: 60 },
      { option: "D", text: "3", correct: false, probability: 10 },
    ],
  },
  {
    id: 8,
    question: "Which country is home to the kangaroo?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "India", correct: false, probability: 10 },
      { option: "B", text: "Australia", correct: true, probability: 70 },
      { option: "C", text: "South Africa", correct: false, probability: 10 },
      { option: "D", text: "Brazil", correct: false, probability: 10 },
    ],
  },
  {
    id: 9,
    question: "Which element has the chemical symbol 'O'?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Gold", correct: false, probability: 10 },
      { option: "B", text: "Oxygen", correct: true, probability: 70 },
      { option: "C", text: "Osmium", correct: false, probability: 10 },
      { option: "D", text: "Oganesson", correct: false, probability: 10 },
    ],
  },
  {
    id: 10,
    question: "What is the currency of Japan?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Yuan", correct: false, probability: 20 },
      { option: "B", text: "Won", correct: false, probability: 20 },
      { option: "C", text: "Yen", correct: true, probability: 50 },
      { option: "D", text: "Dollar", correct: false, probability: 10 },
    ],
  },
  {
    id: 11,
    question: "Which language is the most spoken worldwide?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "English", correct: false, probability: 50 },
      { option: "B", text: "Mandarin Chinese", correct: true, probability: 30 },
      { option: "C", text: "Spanish", correct: false, probability: 10 },
      { option: "D", text: "Hindi", correct: false, probability: 10 },
    ],
  },
  {
    id: 12,
    question: "In what year did World War II end?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "1943", correct: false, probability: 10 },
      { option: "B", text: "1944", correct: false, probability: 20 },
      { option: "C", text: "1945", correct: true, probability: 60 },
      { option: "D", text: "1946", correct: false, probability: 10 },
    ],
  },
  {
    id: 13,
    question: "Which artist painted the Mona Lisa?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Vincent van Gogh", correct: false, probability: 20 },
      { option: "B", text: "Pablo Picasso", correct: false, probability: 20 },
      { option: "C", text: "Leonardo da Vinci", correct: true, probability: 50 },
      { option: "D", text: "Claude Monet", correct: false, probability: 10 },
    ],
  },
  {
    id: 14,
    question: "What is the largest bone in the human body?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Humerus", correct: false, probability: 20 },
      { option: "B", text: "Femur", correct: true, probability: 60 },
      { option: "C", text: "Tibia", correct: false, probability: 10 },
      { option: "D", text: "Fibula", correct: false, probability: 10 },
    ],
  },
  {
    id: 15,
    question: "Which Nobel Prize did Albert Einstein win?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Peace", correct: false, probability: 20 },
      { option: "B", text: "Literature", correct: false, probability: 10 },
      { option: "C", text: "Physics", correct: true, probability: 60 },
      { option: "D", text: "Chemistry", correct: false, probability: 10 },
    ],
  },
  {
    id: 16,
    question: "What is the main ingredient in guacamole?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Tomato", correct: false, probability: 20 },
      { option: "B", text: "Avocado", correct: true, probability: 70 },
      { option: "C", text: "Onion", correct: false, probability: 10 },
      { option: "D", text: "Garlic", correct: false, probability: 10 },
    ],
  },
  {
    id: 17,
    question: "What is the chemical formula for water?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "H2O", correct: true, probability: 70 },
      { option: "B", text: "O2", correct: false, probability: 10 },
      { option: "C", text: "CO2", correct: false, probability: 10 },
      { option: "D", text: "H2", correct: false, probability: 10 },
    ],
  },
  {
    id: 18,
    question: "Which country is known as the Land of the Rising Sun?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "China", correct: false, probability: 10 },
      { option: "B", text: "South Korea", correct: false, probability: 10 },
      { option: "C", text: "Japan", correct: true, probability: 70 },
      { option: "D", text: "Thailand", correct: false, probability: 10 },
    ],
  },
  {
    id: 19,
    question: "What is the capital city of France?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Berlin", correct: false, probability: 10 },
      { option: "B", text: "Madrid", correct: false, probability: 10 },
      { option: "C", text: "Paris", correct: true, probability: 70 },
      { option: "D", text: "Rome", correct: false, probability: 10 },
    ],
  },
  {
    id: 20,
    question: "What is the powerhouse of the cell?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Nucleus", correct: false, probability: 10 },
      { option: "B", text: "Mitochondria", correct: true, probability: 70 },
      { option: "C", text: "Ribosome", correct: false, probability: 10 },
      { option: "D", text: "Chloroplast", correct: false, probability: 10 },
    ],
  },
  {
    id: 21,
    question: "Which country is the largest by area?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Canada", correct: false, probability: 20 },
      { option: "B", text: "Russia", correct: true, probability: 50 },
      { option: "C", text: "China", correct: false, probability: 20 },
      { option: "D", text: "United States", correct: false, probability: 10 },
    ],
  },
  {
    id: 22,
    question: "Who wrote 'Romeo and Juliet'?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "William Shakespeare", correct: true, probability: 70 },
      { option: "B", text: "Charles Dickens", correct: false, probability: 10 },
      { option: "C", text: "Mark Twain", correct: false, probability: 10 },
      { option: "D", text: "Jane Austen", correct: false, probability: 10 },
    ],
  },
  {
    id: 23,
    question: "What is the main ingredient in sushi?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Rice", correct: true, probability: 70 },
      { option: "B", text: "Bread", correct: false, probability: 10 },
      { option: "C", text: "Potato", correct: false, probability: 10 },
      { option: "D", text: "Corn", correct: false, probability: 10 },
    ],
  },
  {
    id: 24,
    question: "What is the currency of the United Kingdom?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Euro", correct: false, probability: 10 },
      { option: "B", text: "Pound Sterling", correct: true, probability: 70 },
      { option: "C", text: "Dollar", correct: false, probability: 10 },
      { option: "D", text: "Yen", correct: false, probability: 10 },
    ],
  },
  {
    id: 25,
    question: "How many continents are there on Earth?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "5", correct: false, probability: 10 },
      { option: "B", text: "6", correct: false, probability: 10 },
      { option: "C", text: "7", correct: true, probability: 70 },
      { option: "D", text: "8", correct: false, probability: 10 },
    ],
  },
  {
    id: 26,
    question: "What does a thermometer measure?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Wind speed", correct: false, probability: 10 },
      { option: "B", text: "Temperature", correct: true, probability: 70 },
      { option: "C", text: "Pressure", correct: false, probability: 10 },
      { option: "D", text: "Distance", correct: false, probability: 10 },
    ],
  },
  {
    id: 27,
    question: "Which organ pumps blood through the human body?",
    difficulty: "easy",
    answers: [
      { option: "A", text: "Lungs", correct: false, probability: 10 },
      { option: "B", text: "Liver", correct: false, probability: 10 },
      { option: "C", text: "Heart", correct: true, probability: 70 },
      { option: "D", text: "Kidney", correct: false, probability: 10 },
    ],
  },
  {
    id: 28,
    question: "Which planet is closest to the Sun?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Venus", correct: false, probability: 20 },
      { option: "B", text: "Mercury", correct: true, probability: 60 },
      { option: "C", text: "Earth", correct: false, probability: 10 },
      { option: "D", text: "Mars", correct: false, probability: 10 },
    ],
  },
  {
    id: 29,
    question: "What is the largest mammal on Earth?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Elephant", correct: false, probability: 20 },
      { option: "B", text: "Blue whale", correct: true, probability: 60 },
      { option: "C", text: "Giraffe", correct: false, probability: 10 },
      { option: "D", text: "Hippopotamus", correct: false, probability: 10 },
    ],
  },
  {
    id: 30,
    question: "How many chambers does the human heart have?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "2", correct: false, probability: 20 },
      { option: "B", text: "4", correct: true, probability: 60 },
      { option: "C", text: "3", correct: false, probability: 10 },
      { option: "D", text: "5", correct: false, probability: 10 },
    ],
  },
  {
    id: 31,
    question: "In which year did the Titanic sink?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "1910", correct: false, probability: 10 },
      { option: "B", text: "1911", correct: false, probability: 20 },
      { option: "C", text: "1912", correct: true, probability: 60 },
      { option: "D", text: "1913", correct: false, probability: 10 },
    ],
  },
  {
    id: 32,
    question: "Who was the first person to walk on the moon?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Buzz Aldrin", correct: false, probability: 20 },
      { option: "B", text: "Yuri Gagarin", correct: false, probability: 10 },
      { option: "C", text: "Neil Armstrong", correct: true, probability: 60 },
      { option: "D", text: "Michael Collins", correct: false, probability: 10 },
    ],
  },
  {
    id: 33,
    question: "Which planet has the most moons?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Jupiter", correct: true, probability: 60 },
      { option: "B", text: "Saturn", correct: false, probability: 20 },
      { option: "C", text: "Mars", correct: false, probability: 10 },
      { option: "D", text: "Uranus", correct: false, probability: 10 },
    ],
  },
  {
    id: 34,
    question: "What is the tallest mountain in the world?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Mount Everest", correct: true, probability: 60 },
      { option: "B", text: "K2", correct: false, probability: 20 },
      { option: "C", text: "Kangchenjunga", correct: false, probability: 10 },
      { option: "D", text: "Lhotse", correct: false, probability: 10 },
    ],
  },
  {
    id: 35,
    question: "Which element is needed for fire to burn?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Hydrogen", correct: false, probability: 10 },
      { option: "B", text: "Oxygen", correct: true, probability: 60 },
      { option: "C", text: "Nitrogen", correct: false, probability: 20 },
      { option: "D", text: "Carbon dioxide", correct: false, probability: 10 },
    ],
  },
  {
    id: 36,
    question: "What is the capital city of Australia?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Sydney", correct: false, probability: 20 },
      { option: "B", text: "Melbourne", correct: false, probability: 10 },
      { option: "C", text: "Canberra", correct: true, probability: 60 },
      { option: "D", text: "Perth", correct: false, probability: 10 },
    ],
  },
  {
    id: 37,
    question: "Which year did World War II end?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "1944", correct: false, probability: 10 },
      { option: "B", text: "1945", correct: true, probability: 60 },
      { option: "C", text: "1946", correct: false, probability: 20 },
      { option: "D", text: "1947", correct: false, probability: 10 },
    ],
  },
  {
    id: 38,
    question: "What is the largest ocean on Earth?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Atlantic Ocean", correct: false, probability: 20 },
      { option: "B", text: "Pacific Ocean", correct: true, probability: 60 },
      { option: "C", text: "Indian Ocean", correct: false, probability: 10 },
      { option: "D", text: "Arctic Ocean", correct: false, probability: 10 },
    ],
  },
  {
    id: 39,
    question: "Which country gifted the Statue of Liberty to the United States?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "France", correct: true, probability: 60 },
      { option: "B", text: "United Kingdom", correct: false, probability: 20 },
      { option: "C", text: "Spain", correct: false, probability: 10 },
      { option: "D", text: "Germany", correct: false, probability: 10 },
    ],
  },
  {
    id: 40,
    question: "Who invented the telephone?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Thomas Edison", correct: false, probability: 20 },
      { option: "B", text: "Alexander Graham Bell", correct: true, probability: 60 },
      { option: "C", text: "Nikola Tesla", correct: false, probability: 10 },
      { option: "D", text: "Guglielmo Marconi", correct: false, probability: 10 },
    ],
  },
  {
    id: 41,
    question: "Which language has the most native speakers?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "English", correct: false, probability: 20 },
      { option: "B", text: "Mandarin Chinese", correct: true, probability: 60 },
      { option: "C", text: "Spanish", correct: false, probability: 10 },
      { option: "D", text: "Hindi", correct: false, probability: 10 },
    ],
  },
  {
    id: 42,
    question: "Which of these metals is the best conductor of electricity?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Gold", correct: false, probability: 20 },
      { option: "B", text: "Silver", correct: true, probability: 60 },
      { option: "C", text: "Copper", correct: false, probability: 10 },
      { option: "D", text: "Iron", correct: false, probability: 10 },
    ],
  },
  {
    id: 43,
    question: "Which country hosted the 2016 Summer Olympics?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Japan", correct: false, probability: 20 },
      { option: "B", text: "Brazil", correct: true, probability: 60 },
      { option: "C", text: "China", correct: false, probability: 10 },
      { option: "D", text: "United Kingdom", correct: false, probability: 10 },
    ],
  },
  {
    id: 44,
    question: "What is the largest desert in the world?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Sahara Desert", correct: false, probability: 20 },
      { option: "B", text: "Antarctic Desert", correct: true, probability: 60 },
      { option: "C", text: "Gobi Desert", correct: false, probability: 10 },
      { option: "D", text: "Arabian Desert", correct: false, probability: 10 },
    ],
  },
  {
    id: 45,
    question: "What is the capital city of Brazil?",
    difficulty: "medium",
    answers: [
      { option: "A", text: "Rio de Janeiro", correct: false, probability: 20 },
      { option: "B", text: "São Paulo", correct: false, probability: 10 },
      { option: "C", text: "Brasília", correct: true, probability: 60 },
      { option: "D", text: "Salvador", correct: false, probability: 10 },
    ],
  },
  {
    id: 46,
    question: "What is the rarest blood type in the world?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "A+", correct: false, probability: 10 },
      { option: "B", text: "O-", correct: false, probability: 20 },
      { option: "C", text: "AB-", correct: true, probability: 50 },
      { option: "D", text: "B+", correct: false, probability: 20 },
    ],
  },
  {
    id: 47,
    question: "Who was the second person to step on the moon?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Neil Armstrong", correct: false, probability: 20 },
      { option: "B", text: "Buzz Aldrin", correct: true, probability: 50 },
      { option: "C", text: "Michael Collins", correct: false, probability: 20 },
      { option: "D", text: "Yuri Gagarin", correct: false, probability: 10 },
    ],
  },
  {
    id: 48,
    question: "What is the longest river in the world?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Amazon River", correct: false, probability: 20 },
      { option: "B", text: "Yangtze River", correct: false, probability: 10 },
      { option: "C", text: "Mississippi River", correct: false, probability: 10 },
      { option: "D", text: "Nile River", correct: true, probability: 50 },
    ],
  },
  {
    id: 49,
    question: "Which scientist is known for developing the theory of relativity?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Isaac Newton", correct: false, probability: 10 },
      { option: "B", text: "Nikola Tesla", correct: false, probability: 20 },
      { option: "C", text: "Albert Einstein", correct: true, probability: 50 },
      { option: "D", text: "Galileo Galilei", correct: false, probability: 20 },
    ],
  },
  {
    id: 50,
    question: "What is the capital city of Iceland?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Helsinki", correct: false, probability: 10 },
      { option: "B", text: "Reykjavik", correct: true, probability: 50 },
      { option: "C", text: "Oslo", correct: false, probability: 20 },
      { option: "D", text: "Stockholm", correct: false, probability: 20 },
    ],
  },
  {
    id: 51,
    question: "Which planet is known as the 'Red Planet'?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Mars", correct: true, probability: 50 },
      { option: "B", text: "Jupiter", correct: false, probability: 20 },
      { option: "C", text: "Saturn", correct: false, probability: 20 },
      { option: "D", text: "Venus", correct: false, probability: 10 },
    ],
  },
  {
    id: 52,
    question: "Which element has the highest melting point?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Iron", correct: false, probability: 20 },
      { option: "B", text: "Gold", correct: false, probability: 20 },
      { option: "C", text: "Tungsten", correct: true, probability: 50 },
      { option: "D", text: "Silver", correct: false, probability: 10 },
    ],
  },
  {
    id: 53,
    question: "Which country has won the most FIFA World Cup titles?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Germany", correct: false, probability: 20 },
      { option: "B", text: "Italy", correct: false, probability: 20 },
      { option: "C", text: "Brazil", correct: true, probability: 50 },
      { option: "D", text: "Argentina", correct: false, probability: 10 },
    ],
  },
  {
    id: 54,
    question: "What is the square root of 1444?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "36", correct: false, probability: 20 },
      { option: "B", text: "38", correct: false, probability: 20 },
      { option: "C", text: "37", correct: true, probability: 50 },
      { option: "D", text: "39", correct: false, probability: 10 },
    ],
  },
  {
    id: 55,
    question: "Which year did the French Revolution begin?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "1789", correct: true, probability: 50 },
      { option: "B", text: "1776", correct: false, probability: 20 },
      { option: "C", text: "1799", correct: false, probability: 20 },
      { option: "D", text: "1804", correct: false, probability: 10 },
    ],
  },
  {
    id: 56,
    question: "Which animal has the longest lifespan?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Elephant", correct: false, probability: 20 },
      { option: "B", text: "Galápagos tortoise", correct: true, probability: 50 },
      { option: "C", text: "Bowhead whale", correct: false, probability: 20 },
      { option: "D", text: "Human", correct: false, probability: 10 },
    ],
  },
  {
    id: 57,
    question: "Who painted the 'Sistine Chapel' ceiling?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Leonardo da Vinci", correct: false, probability: 20 },
      { option: "B", text: "Michelangelo", correct: true, probability: 50 },
      { option: "C", text: "Raphael", correct: false, probability: 20 },
      { option: "D", text: "Donatello", correct: false, probability: 10 },
    ],
  },
  {
    id: 58,
    question: "Which gas is most abundant in Earth's atmosphere?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Oxygen", correct: false, probability: 20 },
      { option: "B", text: "Nitrogen", correct: true, probability: 50 },
      { option: "C", text: "Carbon Dioxide", correct: false, probability: 20 },
      { option: "D", text: "Helium", correct: false, probability: 10 },
    ],
  },
  {
    id: 59,
    question: "In which year did the Berlin Wall fall?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "1987", correct: false, probability: 20 },
      { option: "B", text: "1988", correct: false, probability: 20 },
      { option: "C", text: "1989", correct: true, probability: 50 },
      { option: "D", text: "1990", correct: false, probability: 10 },
    ],
  },
  {
    id: 60,
    question: "What is the name of the longest bone in the human body?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Femur", correct: true, probability: 50 },
      { option: "B", text: "Humerus", correct: false, probability: 20 },
      { option: "C", text: "Tibia", correct: false, probability: 20 },
      { option: "D", text: "Fibula", correct: false, probability: 10 },
    ],
  },
  {
    id: 61,
    question: "Which of the following is not a noble gas?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Neon", correct: false, probability: 20 },
      { option: "B", text: "Helium", correct: false, probability: 20 },
      { option: "C", text: "Hydrogen", correct: true, probability: 50 },
      { option: "D", text: "Xenon", correct: false, probability: 10 },
    ],
  },
  {
    id: 62,
    question: "Which Shakespeare play features the character Shylock?",
    difficulty: "hard",
    answers: [
      { option: "A", text: "Hamlet", correct: false, probability: 20 },
      { option: "B", text: "The Merchant of Venice", correct: true, probability: 50 },
      { option: "C", text: "Othello", correct: false, probability: 20 },
      { option: "D", text: "King Lear", correct: false, probability: 10 },
    ],
  }
]

export default questionData